In [12]:
import torch
import torch.nn as nn

# 예제 데이터: shape (m, n)
m, n = 10, 5
data = torch.randn(m, n)

# Conv1D 입력 형태로 변환: (batch_size, seq_length, num_features)
data = data.unsqueeze(0)  # (1, m, n)

In [13]:
data

tensor([[[ 0.4671,  0.8763,  0.4876, -1.3068, -1.4035],
         [ 1.2523,  0.4195, -0.2915,  0.1997,  0.4328],
         [ 0.7372,  0.5323,  0.4372, -1.7458, -0.0136],
         [-1.0714,  0.9939,  0.1828, -0.8094, -0.5994],
         [-0.9040, -0.7741,  0.1710, -0.8645,  0.0881],
         [-0.2224,  1.5162, -0.6907, -0.3091, -0.6098],
         [-0.1158, -0.3318, -0.8572,  0.3974, -2.7583],
         [-0.4961, -0.3616,  0.5557,  1.3564,  0.4701],
         [-0.9491, -0.5491, -0.5506, -0.7191,  0.9820],
         [-1.4604,  0.1030, -0.7883,  0.6519,  0.4492]]])

In [24]:
conv1d = nn.Conv1d(in_channels=n, out_channels=16, kernel_size=3, padding=1)
output = conv1d(data)
conv1d2 = nn.Conv1d(in_channels=16, out_channels=16, kernel_size=3, padding=1)
output2 = conv1d2(output)

In [ ]:
print(output.shape)
print(output2.shape)

torch.Size([1, 16, 10])
torch.Size([1, 16, 10])


In [ ]:
import einops

outputs = []
outputs.append(output)
outputs.append(output2)

outputs = torch.stack(outputs, dim=1)
print(outputs.shape)

torch.Size([1, 2, 10, 16])


In [ ]:


arranged = einops.rearrange(outputs, 'b k c seq -> b seq (k c)')
print(arranged.shape)

torch.Size([1, 10, 32])


In [38]:
print(arranged)

tensor([[[-6.7431e-01, -1.5517e-01,  2.1028e-01,  3.3929e-01,  9.0354e-01,
          -1.2770e+00,  5.2330e-01, -2.8694e-01,  7.1806e-03,  2.8178e-01,
          -3.2743e-01,  3.8808e-02, -7.1193e-01,  1.3042e-01, -5.5582e-01,
          -4.9921e-01,  2.3593e-01, -3.3445e-01, -8.1384e-02,  7.1686e-02,
          -1.7867e-01, -1.4837e-01, -1.3520e-01,  5.9450e-02,  1.1977e-01,
          -2.4084e-01,  2.1731e-01, -5.0586e-01,  3.1905e-01,  1.8180e-01,
          -3.7995e-02, -4.6103e-01],
         [ 5.6272e-02, -1.4077e+00, -8.8103e-01, -4.7902e-01, -2.9560e-01,
          -3.8936e-01, -3.5604e-01, -2.1221e-01, -5.3438e-02,  2.9841e-01,
          -4.2561e-01, -6.2395e-02, -2.2724e-01,  4.0242e-01, -3.2500e-01,
           1.9796e-01, -5.6061e-02, -3.9490e-01,  1.3214e-01, -3.0329e-01,
           1.4091e-01,  1.5008e-01,  2.4767e-01,  1.7521e-01,  3.5152e-01,
           3.6869e-01,  1.5806e-01,  3.1691e-01,  2.5838e-01,  1.5097e-01,
          -3.4957e-01, -7.1892e-02],
         [-3.9484e-01,  2.

In [39]:
output = einops.rearrange(output, 'b c seq -> b seq c')
output

tensor([[[-0.6743, -0.1552,  0.2103,  0.3393,  0.9035, -1.2770,  0.5233,
          -0.2869,  0.0072,  0.2818, -0.3274,  0.0388, -0.7119,  0.1304,
          -0.5558, -0.4992],
         [ 0.0563, -1.4077, -0.8810, -0.4790, -0.2956, -0.3894, -0.3560,
          -0.2122, -0.0534,  0.2984, -0.4256, -0.0624, -0.2272,  0.4024,
          -0.3250,  0.1980],
         [-0.3948,  0.2471, -0.1964,  0.1556,  0.1896, -0.2779, -0.3507,
           0.1036, -0.3742, -0.1720, -1.1277, -0.5617, -0.6690,  0.3034,
          -0.5107, -0.1495],
         [ 0.5621, -0.1554, -0.1530,  0.2496, -0.2561, -0.0752,  0.1903,
           0.4857, -0.6162, -0.0191, -0.5838, -0.6915, -0.0964,  0.6812,
          -0.0931, -0.4730],
         [-0.6678,  0.0192, -0.1345,  0.6101, -0.6585,  0.4190,  0.2103,
          -0.3670, -1.1113, -0.4485, -0.1610, -0.3692,  0.5227,  0.3804,
           0.8308,  0.0975],
         [ 0.4085,  0.0434, -0.1433,  0.9542, -0.1745,  0.1434,  0.8402,
          -0.7726, -1.1439,  0.3526,  0.0599, -0.284

In [31]:
print(output)
print(output2)

tensor([[[-0.6743,  0.0563, -0.3948,  0.5621, -0.6678,  0.4085, -0.0717,
          -0.2183, -0.7977, -0.0242],
         [-0.1552, -1.4077,  0.2471, -0.1554,  0.0192,  0.0434,  0.4258,
          -0.2293,  1.0695,  0.3169],
         [ 0.2103, -0.8810, -0.1964, -0.1530, -0.1345, -0.1433,  0.0226,
          -0.3197,  0.7915,  0.0347],
         [ 0.3393, -0.4790,  0.1556,  0.2496,  0.6101,  0.9542,  1.4948,
          -0.1894,  0.1711,  0.1877],
         [ 0.9035, -0.2956,  0.1896, -0.2561, -0.6585, -0.1745,  0.2989,
          -0.5169,  0.2173,  0.0319],
         [-1.2770, -0.3894, -0.2779, -0.0752,  0.4190,  0.1434,  0.4640,
           0.0590,  0.1838,  0.6811],
         [ 0.5233, -0.3560, -0.3507,  0.1903,  0.2103,  0.8402,  0.3016,
           0.6466, -0.4001,  0.1076],
         [-0.2869, -0.2122,  0.1036,  0.4857, -0.3670, -0.7726,  0.0267,
          -0.3383,  0.1191,  0.0234],
         [ 0.0072, -0.0534, -0.3742, -0.6162, -1.1113, -1.1439, -0.6135,
           0.5214, -0.0519, -1.1224],
 

In [ ]:
from einops import rearrange

# 변환된 코드
data = rearrange(data, 'b seq feats -> b feats seq')
output = conv1d(data)
print(output.shape)
print(output)

torch.Size([1, 1, 10])
tensor([[[ 0.3459,  0.5755,  0.0019, -0.3402,  1.0256,  0.9840,  0.8113,
           0.0845, -0.0122, -0.0751]]], grad_fn=<ConvolutionBackward0>)


In [1]:
from utils import prepare_data_for_CNN_LSTM

region = "Seoul"
if region == "Jeonju":
    columns_to_remove = ["CA_TOT", "CA_MID", "STN", "IR", "PA", "IX", "PS", "지점", "위도", "경도"]
else:
    columns_to_remove = ["CA_TOT", "CA_MID", "STN", "IR", "PA", "PS", "지점", "위도", "경도"]

df = prepare_data_for_CNN_LSTM(region.lower(), columns_to_remove)
df.shape

/home/sangwon/nlplab_leaderboard2/Junho/JH/CNN_LSTM/utils.py:119: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[pm_columns] = df[pm_columns].applymap(lambda x: np.nan if x <= 0 else x)


(10016, 21)

(10016, 4)

In [48]:
!ls ../../collect_data/filtered/kma

2018  2019  2020  2021	2022  merged
